name: Deploy Infrastructure

on: [push]

jobs:
  tf_fmt:
    name: Deploy AWS Infra
    runs-on: ubuntu-latest
    steps:

    
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      
    - name: Checkout Repo
      uses: actions/checkout@v1

    # - name: Change to Terraform Directory
    #   run: cd terraform && cd terraform

    - name: Print working dir
      run: pwd
    
    - name: check if dir is empty
      run: ls && cd ./terraform

    # - name: check prev folder
    #   run: cd .. && ls

    - name: Terraform Init
      run: terraform -chdir=terraform init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    - name: Terraform Validate
      run: terraform -chdir=terraform plan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    - name: Sync S3
      if: always()
      uses: jakejarvis/s3-sync-action@master
      env:
        SOURCE_DIR: './src'
        AWS_REGION: 'ap-southeast-1'
        AWS_S3_BUCKET: 'aws-terraform-practice-vsujeesh'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}